// <auto-generated />
namespace UserManagementApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserIDRelationAddedToPermissions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserIDRelationAddedToPermissions));
        
        string IMigrationMetadata.Id
        {
            get { return "202206050744516_UserIDRelationAddedToPermissions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
